// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;




/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTXSF1w_2ykLs5621xvSxdUxzw5tp2vAI',
    appId: '1:420894404559:web:65c269c701a24e5086acba',
    messagingSenderId: '420894404559',
    projectId: 'first-18e94',
    authDomain: 'first-18e94.firebaseapp.com',
    storageBucket: 'first-18e94.appspot.com',
    measurementId: 'G-53RHF6DSL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjVZn1R7NchI61Fs9wfLI4MwcYvZ6evs',
    appId: '1:420894404559:android:c776ddfda0faf99d86acba',
    messagingSenderId: '420894404559',
    projectId: 'first-18e94',
    storageBucket: 'first-18e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiCyGnEmYzI52qKcNM-RP7PxEdNyruMcQ',
    appId: '1:420894404559:ios:a49b21531cd4293086acba',
    messagingSenderId: '420894404559',
    projectId: 'first-18e94',
    storageBucket: 'first-18e94.appspot.com',
    iosClientId: '420894404559-fooilno8olo4kdagv27th88ibfpqm9it.apps.googleusercontent.com',
    iosBundleId: 'com.example.blinkit',
  );
}
